ErrorCodes = {
    "INVALID_EMAIL": "INVALID_EMAIL",
    "EMAIL_ALREADY_REGISTERED": "EMAIL_ALREADY_REGISTERED",
    "INVALID_TOKEN": "INVALID_TOKEN",
    "INVALID_CREDENTIALS": "INVALID_CREDENTIALS",
    "INVALID_USER": "INVALID_USER",
    "INVALID_PASSWORD": "INVALID_PASSWORD",
    "INVALID_USER_NOT_FOUND": "INVALID_USER_NOT_FOUND",
    "INTERNAL_SERVER_ERROR": "INTERNAL_SERVER_ERROR"
}